// Curated legal rights & accommodations directory for cancer survivors.
// Educational information only — not legal advice.

export const directoryTopics = [
  { id: 'fmla', name: 'FMLA', color: 'from-blue-500 to-indigo-600' },
  { id: 'ada', name: 'ADA', color: 'from-emerald-500 to-teal-600' },
  { id: 'state', name: 'State-Specific Laws', color: 'from-violet-500 to-purple-600' },
  { id: 'accommodations', name: 'Workplace Accommodations', color: 'from-rose-500 to-pink-600' },
  { id: 'insurance', name: 'Insurance & Benefits', color: 'from-amber-500 to-orange-600' },
  { id: 'privacy', name: 'Disclosure & Privacy', color: 'from-sky-500 to-cyan-600' },
];

export const directoryEntries = [
  // ---------------- FMLA ----------------
  {
    id: 'fmla-basics',
    topic: 'fmla',
    title: 'What is FMLA and am I eligible?',
    summary: 'The Family and Medical Leave Act gives eligible employees up to 12 weeks of unpaid, job-protected leave per year.',
    details: 'You are generally eligible if you: (1) work for a covered employer (private employers with 50+ employees, all public agencies and schools), (2) have worked there at least 12 months, (3) have worked at least 1,250 hours over the past 12 months, and (4) work at a location where the employer has 50+ employees within 75 miles. Cancer treatment and recovery qualify as a "serious health condition."',
    tags: ['eligibility', 'leave', '12 weeks', 'job protection'],
    link: { label: 'DOL FMLA Overview', url: 'https://www.dol.gov/agencies/whd/fmla' },
  },
  {
    id: 'fmla-intermittent',
    topic: 'fmla',
    title: 'Intermittent FMLA leave for treatment',
    summary: 'You can take FMLA leave in separate blocks of time — for example, a few hours for chemo appointments or recovery days.',
    details: 'Intermittent leave lets you take FMLA in the smallest increments your employer\'s payroll system tracks (often 15 minutes to 1 hour). This is especially useful for ongoing treatments, follow-up appointments, or managing fatigue flare-ups. Your employer may ask for a medical certification showing the medical necessity of intermittent leave and its expected frequency.',
    tags: ['intermittent', 'chemo', 'appointments', 'treatment schedule'],
  },
  {
    id: 'fmla-benefits',
    topic: 'fmla',
    title: 'Health insurance during FMLA leave',
    summary: 'Your employer must maintain your group health coverage on the same terms while you are on FMLA leave.',
    details: 'During FMLA leave, your employer must continue your health insurance as if you were still working. You remain responsible for your usual share of premiums. When you return, you must be restored to the same or an equivalent job with equivalent pay, benefits, and working conditions.',
    tags: ['health insurance', 'premiums', 'reinstatement', 'return to work'],
  },
  {
    id: 'fmla-certification',
    topic: 'fmla',
    title: 'Medical certification requirements',
    summary: 'Employers may require a medical certification form completed by your healthcare provider to approve FMLA leave.',
    details: 'Your employer must give you at least 15 calendar days to return the certification. The form asks about the medical necessity of leave — not your full diagnosis details. Your employer cannot ask for your complete medical records. Recertification can generally be requested no more than every 30 days, with exceptions.',
    tags: ['certification', 'doctor', 'paperwork', 'medical records'],
  },
  // ---------------- ADA ----------------
  {
    id: 'ada-basics',
    topic: 'ada',
    title: 'Does the ADA protect cancer survivors?',
    summary: 'Yes. Cancer — current or in remission — is virtually always a covered disability under the ADA as amended in 2008.',
    details: 'The Americans with Disabilities Act protects employees of companies with 15+ employees from discrimination based on disability. Under the ADA Amendments Act (ADAAA), cancer qualifies even when in remission, because it substantially limits normal cell growth when active. This means you are protected from discrimination and entitled to reasonable accommodations both during and after treatment.',
    tags: ['disability', 'remission', 'discrimination', 'protection'],
    link: { label: 'EEOC: Cancer in the Workplace', url: 'https://www.eeoc.gov/laws/guidance/questions-answers-about-cancer-workplace-and-americans-disabilities-act-ada' },
  },
  {
    id: 'ada-reasonable',
    topic: 'ada',
    title: 'What counts as a "reasonable accommodation"?',
    summary: 'Any change to the work environment or how a job is done that enables you to perform essential functions — unless it causes undue hardship.',
    details: 'Common examples for survivors: modified work schedules, telework, rest breaks, ergonomic equipment, reassignment of marginal tasks, leave for treatment beyond FMLA, a quieter workspace for concentration issues, and temperature control. Employers must engage in an "interactive process" — a good-faith dialogue about what will work.',
    tags: ['reasonable accommodation', 'interactive process', 'undue hardship', 'telework', 'schedule'],
  },
  {
    id: 'ada-retaliation',
    topic: 'ada',
    title: 'Protection from retaliation',
    summary: 'It is illegal for an employer to punish you for requesting accommodations or filing a discrimination complaint.',
    details: 'Retaliation includes demotion, reduced hours, exclusion from meetings or opportunities, harassment, or termination after you assert your rights. If you believe you have experienced retaliation, document everything with dates and details, and consider filing a charge with the EEOC within 180 days (300 days in some states).',
    tags: ['retaliation', 'EEOC', 'complaint', 'termination', 'documentation'],
  },
  {
    id: 'ada-medical-exams',
    topic: 'ada',
    title: 'Limits on medical questions and exams',
    summary: 'Employers can only ask disability-related questions or require medical exams in limited, job-related circumstances.',
    details: 'Before a job offer, employers cannot ask about cancer history at all. After an offer, they can require a medical exam only if required of all entering employees in that job category. For current employees, questions must be job-related and consistent with business necessity — for example, to support an accommodation request.',
    tags: ['medical exam', 'interview', 'job offer', 'questions', 'hiring'],
  },
  // ---------------- State-specific ----------------
  {
    id: 'state-fair-employment',
    topic: 'state',
    title: 'State fair employment laws (often broader than the ADA)',
    summary: 'Many states protect employees of smaller companies and offer stronger remedies than federal law.',
    details: 'Examples: California\'s FEHA applies to employers with 5+ employees; New York\'s Human Rights Law applies to all employers; New Jersey\'s LAD has no minimum employee count. If your employer is too small for ADA coverage (under 15 employees), check your state\'s fair employment agency — you may still be fully protected.',
    tags: ['FEHA', 'small employer', 'state law', 'human rights law'],
  },
  {
    id: 'state-paid-leave',
    topic: 'state',
    title: 'State paid family and medical leave programs',
    summary: 'A growing number of states offer paid medical leave — unlike the unpaid federal FMLA.',
    details: 'States with paid family/medical leave programs include California, New York, New Jersey, Washington, Massachusetts, Connecticut, Oregon, Colorado, Maryland, Delaware, Minnesota, and Rhode Island (list continues to grow). Benefits typically replace 60–90% of wages for 6–12 weeks. These often run concurrently with FMLA but provide income while you recover.',
    tags: ['paid leave', 'wage replacement', 'PFML', 'state programs'],
  },
  {
    id: 'state-disability-insurance',
    topic: 'state',
    title: 'State disability insurance (SDI)',
    summary: 'California, New York, New Jersey, Rhode Island, Hawaii, and Puerto Rico require short-term disability coverage.',
    details: 'State disability insurance provides partial wage replacement when you cannot work due to a non-work-related illness like cancer. Apply through your state\'s program (e.g., California EDD, New York State Insurance Fund). Payments typically last 26–52 weeks depending on the state and your medical certification.',
    tags: ['SDI', 'short-term disability', 'wage replacement', 'EDD'],
  },
  {
    id: 'state-where-to-check',
    topic: 'state',
    title: 'How to find your state\'s specific protections',
    summary: 'Start with your state\'s fair employment agency and department of labor.',
    details: 'Search "[your state] fair employment agency" and "[your state] paid medical leave." The Job Accommodation Network (askjan.org) and Triage Cancer (triagecancer.org) maintain state-by-state charts of employment and insurance laws written for cancer patients and survivors.',
    tags: ['resources', 'state agency', 'triage cancer', 'JAN'],
    link: { label: 'Triage Cancer State Resources', url: 'https://triagecancer.org/statelaws' },
  },
  // ---------------- Accommodations ----------------
  {
    id: 'acc-how-to-request',
    topic: 'accommodations',
    title: 'How to request an accommodation',
    summary: 'No magic words needed — but putting your request in writing creates a record and starts the interactive process.',
    details: 'You can request an accommodation verbally or in writing, at any time. Best practice: send a short email to HR or your supervisor stating you have a medical condition and need a work adjustment. You do NOT need to name your diagnosis. Example: "Due to a medical condition, I\'m requesting a modified schedule while I complete treatment." Keep copies of everything.',
    tags: ['request', 'writing', 'email', 'HR', 'interactive process'],
  },
  {
    id: 'acc-fatigue',
    topic: 'accommodations',
    title: 'Accommodations for cancer-related fatigue',
    summary: 'Flexible scheduling, rest breaks, telework, and workload adjustments are commonly granted for fatigue.',
    details: 'Effective options include: a later start time, scheduled rest breaks in a private area, working from home on low-energy days, temporarily reduced hours, front-loading important tasks in the morning, and shifting marginal duties to colleagues. Track your energy patterns for a week to ground your request in specifics.',
    tags: ['fatigue', 'rest breaks', 'flexible schedule', 'remote work', 'energy'],
  },
  {
    id: 'acc-cognitive',
    topic: 'accommodations',
    title: 'Accommodations for "chemo brain" (cognitive changes)',
    summary: 'Written instructions, quiet workspaces, task management tools, and extended deadlines can offset concentration and memory changes.',
    details: 'Ask for: instructions in writing or by email, noise-cancelling headphones or a quieter workspace, calendar/task-management apps, breaking large projects into milestones, recording meetings, and checking in with your supervisor weekly rather than being monitored constantly.',
    tags: ['chemo brain', 'memory', 'concentration', 'cognitive', 'quiet'],
  },
  {
    id: 'acc-denied',
    topic: 'accommodations',
    title: 'What if my accommodation request is denied?',
    summary: 'Ask for the reason in writing, propose alternatives, and escalate through HR — denial must be based on undue hardship.',
    details: 'An employer can deny a specific accommodation but must still explore alternatives that work. Steps: (1) request the denial reason in writing, (2) offer alternative accommodations, (3) involve HR if your supervisor denied it, (4) contact the Job Accommodation Network for free expert suggestions, (5) if the process stalls, you may file an EEOC charge within 180/300 days.',
    tags: ['denied', 'undue hardship', 'appeal', 'alternatives', 'EEOC'],
    link: { label: 'Job Accommodation Network', url: 'https://askjan.org' },
  },
  // ---------------- Insurance & Benefits ----------------
  {
    id: 'ins-cobra',
    topic: 'insurance',
    title: 'COBRA: keeping insurance if you leave your job',
    summary: 'COBRA lets you keep your employer health plan for up to 18–36 months after leaving — you pay the full premium.',
    details: 'If you resign, are laid off, or have hours reduced below benefits eligibility, COBRA lets you continue the exact same coverage for up to 18 months (sometimes 29–36 months with a disability extension). You pay the full premium plus a 2% fee. Compare COBRA costs against ACA marketplace plans — a serious diagnosis often makes keeping your current network worthwhile.',
    tags: ['COBRA', 'quit', 'laid off', 'premium', 'continuation'],
  },
  {
    id: 'ins-ssdi',
    topic: 'insurance',
    title: 'Social Security Disability (SSDI) and cancer',
    summary: 'If you cannot work for 12+ months, SSDI may apply — some cancers qualify for expedited "Compassionate Allowances."',
    details: 'SSDI requires that your condition prevents substantial work for at least 12 months. Certain diagnoses (e.g., metastatic disease, some blood cancers) are on the Compassionate Allowances list and get fast-tracked approval. There is a 5-month waiting period for benefits, and Medicare eligibility begins 24 months after benefits start.',
    tags: ['SSDI', 'social security', 'compassionate allowance', 'medicare', 'long-term'],
  },
  {
    id: 'ins-std-ltd',
    topic: 'insurance',
    title: 'Short-term and long-term disability insurance',
    summary: 'Employer-provided STD/LTD policies replace part of your income during treatment — file before leaving payroll.',
    details: 'Short-term disability typically covers 60–70% of wages for 3–6 months; long-term disability picks up after and can pay until retirement age. Check your summary plan description for the definition of disability, elimination periods, and whether benefits offset SSDI. File claims promptly — coverage often depends on being actively employed when disability begins.',
    tags: ['STD', 'LTD', 'income', 'disability insurance', 'claims'],
  },
  {
    id: 'ins-erisa',
    topic: 'insurance',
    title: 'Appealing a denied insurance claim',
    summary: 'You have the right to internal appeals and, for most employer plans, an independent external review.',
    details: 'For health claims: request the denial reason and your claim file (free), file an internal appeal (usually within 180 days), then request external review by an independent physician. For disability claims under ERISA, exhaust the plan\'s appeal process carefully — the appeal record is usually what a court will review later. Nonprofits like Triage Cancer and the Patient Advocate Foundation offer free help.',
    tags: ['appeal', 'denial', 'ERISA', 'external review', 'patient advocate'],
  },
  // ---------------- Disclosure & Privacy ----------------
  {
    id: 'priv-disclosure',
    topic: 'privacy',
    title: 'Do I have to tell my employer I had cancer?',
    summary: 'No. Disclosure is your choice — you only need to share enough medical information to support a specific request.',
    details: 'You are never required to disclose a diagnosis to get hired or keep a job. If you request FMLA leave or an ADA accommodation, you must provide medical documentation supporting that request, but it can describe functional limitations ("needs treatment requiring absences") rather than naming cancer. Weigh timing: disclosing before performance issues arise creates a cleaner record of protected status.',
    tags: ['disclosure', 'diagnosis', 'privacy', 'telling employer', 'choice'],
  },
  {
    id: 'priv-confidentiality',
    topic: 'privacy',
    title: 'Who can see my medical information at work?',
    summary: 'The ADA requires employers to keep medical information in separate, confidential files with very limited access.',
    details: 'Medical information must be stored separately from your personnel file. Supervisors may only be told about necessary work restrictions and accommodations — not your diagnosis. First aid personnel and government investigators may access it in limited circumstances. If a coworker or manager spreads your medical information, that itself may violate the ADA.',
    tags: ['confidentiality', 'medical file', 'HR', 'coworkers', 'gossip'],
  },
  {
    id: 'priv-genetic',
    topic: 'privacy',
    title: 'GINA: genetic information protections',
    summary: 'The Genetic Information Nondiscrimination Act bars employers from using genetic test results or family cancer history against you.',
    details: 'GINA (15+ employee employers) prohibits requesting, requiring, or using genetic information — including BRCA test results and family medical history — in any employment decision. Health insurers also cannot use genetic information for eligibility or premiums. GINA does not cover life, disability, or long-term-care insurance, so consider timing genetic tests accordingly.',
    tags: ['GINA', 'genetic testing', 'BRCA', 'family history'],
  },
  {
    id: 'priv-references',
    topic: 'privacy',
    title: 'Job hunting: gaps, references, and background checks',
    summary: 'Employment gaps from treatment don\'t have to be explained medically — and past employers can\'t disclose your diagnosis.',
    details: 'You may describe a treatment gap as "time off for a personal health matter, now resolved." Prospective employers cannot ask about disability or medical history before a job offer. Former employers who disclose your medical information in a reference may violate the ADA\'s confidentiality rules. Focus interviews on your readiness and skills.',
    tags: ['job search', 'resume gap', 'references', 'background check', 'interview'],
  },
];